### ISSUE TITLE
`datafy` namespace is not available in magic

### ISSUE THREAD

**Issue by skydread1** [nasser/magic#219]
## Problem

The protocols `Datafiable` and `Navigable` are not present in `clojure.core.protocols`.

The namespace `datafy` is not present in `stdlib`.

**Comment by skydread1** [comment]
## What works

I added the `Datafiable` and `Navigable` protocols to `clojure.core.protocols`.

I added the `clojure.datafy` namespace to `stdlib`.

I added `requiring-resolve` to `clojure.core` because it is called by datafy. I ignored the `serialized-require` because I did not know how to deal with `clojure.lang.RT/REQUIRE_LOCK`.

I was able to use datafy in the nostrand repl.

## What doesn't not work yet

However, after adding `clojure.datafy` to the build namespace it is ignored and not build for the bootstrapping.

I was able to generate the `clojure.datafy.clj.dll` via the nostrand repl and added it to `nostrand/references` but still, it is ignored while doing the bootstrapping.

**Comment by skydread1** [comment]
## Update

It is bootstrapping now.

Another issue encountered was the fact that the `clojure-clr` version was using in [datafy.clj](https://github.com/clojure/clojure-clr/blob/master/Clojure/Clojure.Source/clojure/datafy.clj#L27)
```clojure
(-> x class .Name symbol) ;; getName
```
However .Name won't return the fully qualified name so I replaced it by `str` which seems to do the trick.

**Comment by nasser** [comment]
merged! thank you!

**Comment by nasser** [comment]
heads up -- adding vars to `clojure.core` breaks the bootstrap because we compile clojure.core last. i added a mechanism to `build.clj` to work around it [here](https://github.com/nasser/magic/blob/master/build.clj#L15). that will have to be updated whenever new vars are introduced to `clojure.core` until we resolve the load path issue that prevents `clojure.core` from compiling first during bootstrap.
