### ISSUE TITLE
case expressions cannot handle sparse switch type

### ISSUE THREAD

**Issue by timsgardner** [nasser/magic#97]
This bug applies in Arcadia's ClojureCLR, haven't tested in MAGIC yet (since `case` isn't in MAGIC yet).

```clojure
(defn rand-string [n]
  (apply str
    (repeatedly n
      #(Char/ConvertFromUtf32 (rand-int 256)))))

(defn case-expression-test [string-len string-number]
  (let [strs (->> (repeatedly #(rand-string string-len))
                  distinct
                  (take string-number)
                  set)
        expr-f (eval
                 `(fn [val#]
                    (case val#
                      ~@(->> strs
                             (map-indexed (fn [i s] [s i]))
                             (apply concat)))))]
    (= (count strs)
       (count (set (map expr-f strs))))))
```
Then:
```
user=> (case-expression-test 100 300)
íËEÀyÑ¾¢Ö1hèÊyo»%gÍP¡±1ZþÝ2(Ð¥Íjáý»¨²£ìP?)ÒàmoG	U$«è,ºÐ"ÃU*ñEq×ä{9÷
* user/evalfn
* clojure/core/mapfn
  clojure.lang.LazySeq.sval ()
  NO_CLASS.NO_METHOD
  clojure.lang.LazySeq.seq ()
  NO_CLASS.NO_METHOD
  clojure.lang.RT.seq (object)
* clojure/core/seq
* clojure/core/reduce1
* clojure/core/set
* user/case-expression-test
* user/eval
  clojure.lang.Compiler.eval (object)
  clojure.lang.Compiler.eval (object)
* clojure/core/eval
* arcadia/internal/socket-repl/game-thread-evalfnfn
```
In other words, a case expression with 300 branches, each of which has 200 unique strings, throws an error when applied to each of those strings. It does *not* throw this error when applied to fewer strings (like, `(case-expression-test 20 20)`).

**Comment by timsgardner** [comment]
Throws the error with shorter strings too, the error seems to have to do with the length of the `case` expression:
```
user=> (case-expression-test 20 300)
System.ArgumentException: No matching clause: mxÓ?½:ñµXmïÛaÐÚ
* user/evalfn
* clojure/core/mapfn
  clojure.lang.LazySeq.sval ()
  NO_CLASS.NO_METHOD
  clojure.lang.LazySeq.seq ()
  NO_CLASS.NO_METHOD
  clojure.lang.RT.seq (object)
* clojure/core/seq
* clojure/core/reduce1
* clojure/core/set
* user/case-expression-test
* user/eval
  clojure.lang.Compiler.eval (object)
  clojure.lang.Compiler.eval (object)
* clojure/core/eval
* arcadia/internal/socket-repl/game-thread-evalfnfn
```

**Comment by nasser** [comment]
this seems to do it, taken from an expansion of the macro above: https://gist.github.com/nasser/41292400168fa044358191bb6e8e6e57

**Comment by nasser** [comment]
some relevant data about the failing cases:
* because of how spread out the hashes are the resulting jump table would require **4,269,172,013 entries**
* this number is well over **8,192**, the maximum table size that the Clojure standard library supports as encoded in `clojure.core/max-switch-table-size`
* this number is only slightly less than the VM imposed maximum table size of **4,294,967,295**, the maximum value of an unsinged integer (see ECMA 335 III.3.66).

Exceeding `clojure.core/max-switch-table-size` results in a case with a switch type of `:sparse` as opposed to the more common `:compact`. The JVM implementation [uses this information](https://github.com/clojure/clojure/blob/30a36cbe0ef936e57ddba238b7fa6d58ee1cbdce/src/jvm/clojure/lang/Compiler.java#L8854) to emit *two different kinds of switch bytecode*, `tableswitch` or `lookupswitch` (the difference is explained well [here](https://stackoverflow.com/questions/10287700/difference-between-jvms-lookupswitch-and-tableswitch)). the CLR only has a single switch opcode, so a similar distinction cannot be made. in any case, the ClojureCLR [implementation appears to be incomplete](https://github.com/clojure/clojure-clr/blob/0fe1bf63212d414fee66af98a658979f860a6434/Clojure/Clojure/CljCompiler/Ast/CaseExpr.cs#L241) -- it just writes the branch labels into the switch opcode as they are, without providing any padding to default labels.

it is not clear why MAGIC appears to hang when trying to compile this form. we are close enough to the VM limit to be pathological and I wonder if we are hitting implementation detail edge cases of Mono or System.Reflection.Emit when attempting to generate such an enormous jump table.

**Comment by nasser** [comment]
reproducible with integers as well

```clj
(defmacro case-spam-int []
  (let [ints (repeatedly 300 #(rand-int Int32/MaxValue))]
    `(case 1
       1 1
       ~@(mapcat (fn [i] `(~i ~i)) ints))))

(case-spam-int)
;; Exception System.ArgumentException: No matching clause: 1
```

the common element is the `:sparse` switch type. updating issue title to reflect.

**Comment by nasser** [comment]
MAGIC now returns the expected value where ClojureCLR throws an exception.

```clj
user> (magic.api/eval problems/sparse-case-strings)
0
user> (eval problems/sparse-case-strings)
Exception System.ArgumentException: No matching clause: {wzB=&8LFE
user> (magic.api/eval problems/sparse-case-ints)
1
user> (eval problems/sparse-case-ints)
```

The current implementation is a linear search, so it will be categorically slower than the expected performance of `case`. Optimizing this expression is being tracked in #98.
